version: '3'
services:
  app:
    build: .
    entrypoint: "/bin/bash"
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    env_file:
      - .env
    ports:
      - 8080:8080
      - 8501:8501
    depends_on:
      - database
  database:
    image: postgres:15.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_manager
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data