[logging]
LOG_LEVEL = "DEBUG"
FORMATTER = "%(asctime)s - %(levelname)s - %(message)s"

[database]
dialect = "postgresql"
username = "postgres"
password = "postgres"
host = "database"
port = "5432"
database = "task_manager"

[users]
credentials = '''
[
    {
        "username": "user",
        "password": "pass"
    }
]
'''